### ISSUE TITLE
SQL INSERT DOES NOT WORK

### ISSUE THREAD

**Issue by NiniMine** [Limework/skript-db#11]
What does it mean? (`last sql error`)
`Invalid argument value: java.io.NotSerializableException`

my code:
`execute "INSERT INTO disky (id, title, description, pattern, type, addon_name, addon_link, addon_version, last_updated, event_values, event_cancellable, type_usage, depends, tags) VALUES (%{_id}%, %{_title}%, %{_description}%, %{_pattern}%, %{_type}%, %{_addon_name}%, %{addon_link}%, %{_addon_version}%, %{_last_updated}%, %{_event_values}%, %{_event_cacellable}%, %{_type_usage}%, %{_depends}%, %{_filtered_tags}%)" in {sql}`

If I don't use variables, then it works. But I don't know if it's one variable or all variables.
The SQL Structure
![image](https://user-images.githubusercontent.com/66845615/119516002-a65f8300-bd76-11eb-9b18-76db985de900.png)

**Comment by Govindass** [comment]
this happens due to trying to insert unserializable data type

**Comment by NiniMine** [comment]
What exactly should I convert? the variables?

**Comment by Govindass** [comment]
yes

**Comment by Govindass** [comment]
yes

**Comment by Govindass** [comment]
you are modifying disk variables too often, not related to this addon

**Comment by NiniMine** [comment]
okay thanks
