### ISSUE TITLE
INSERT INTO BUG?

### ISSUE THREAD

**Issue by PMencrp** [Limework/skript-db#13]
execute "INSERT INTO `user` (`playeruuid`,`playerid`) VALUES (%uuid of player%,%player%) ON DUPLICATE KEY UPDATE `playeruuid`=VALUES(`playeruuid`),`playerid`=VALUES(`playerid`)" in {-sql}

This is my code and this code doesn't work
The reason is because my values contain variables
If my value is 123 or ""abc"" today, there will be no error
Here is a screenshot of my error

![image](https://user-images.githubusercontent.com/37236933/123499726-5c1a3c00-d66b-11eb-8fd6-69ec2778da72.png)

My version is the latest version

**Comment by PMencrp** [comment]
i was try change the player to a var or name of player but still don't work

**Comment by PMencrp** [comment]
execute "INSERT INTO user (playeruuid, playerid) VALUES (%uuid of player%,%name of player%)" in {-sql}

still don't work

**Comment by PMencrp** [comment]
![image](https://user-images.githubusercontent.com/37236933/123500867-9e477b80-d673-11eb-8df6-2df1f0422607.png)

**Comment by ham1255** [comment]
https://github.com/Limework/skript-db/releases/tag/1.3.2

**Comment by PMencrp** [comment]
yep i use this version

**Comment by PMencrp** [comment]
aww I tried to drop the skript version back to 2.5 and amazingly it worked!

**Comment by ham1255** [comment]
yes skript 2.6 broke something 
@GovindasOM you might need to look at this

**Comment by GovindasOM** [comment]
I wasn't sure how to fix this so I asked TPGamesNL for help, could you try this jar if it solves your issue? (I do not have time to test it myself right now)
[skript-db.zip](https://github.com/Limework/skript-db/files/6719929/skript-db.zip)
