### ISSUE TITLE
Statements not working when executed within a skript loop

### ISSUE THREAD

**Issue by bloggy** [Limework/skript-db#9]
I made a test skript:
```
command /testrun [<offlineplayer>]:
	trigger:
		loop 5 times:
			make console execute command "/test"

command /test [<offlineplayer>]:
	trigger:
		execute "SELECT points FROM `test` WHERE `id` = 1;" in {sql} and store the result in {_r::*}
		set {_points} to 0
		if {_r::points::1} is set:
			set {_points} to {_r::points::1}
		set {_id} to 1
		add 10 to {_points}
		execute "INSERT INTO `test` (`id`, `points`) VALUES (%{_id}%, %{_points}%) ON DUPLICATE KEY UPDATE `points` = %{_points}%" in {sql}
		broadcast "INSERT INTO `test` (`id`, `points`) VALUES (%{_id}%, %{_points}%) ON DUPLICATE KEY UPDATE `points` = %{_points}%"
```
Now I execute "/testrun"
It should add 5x 10 points to the points field in the mysql table, but the result is that it only adds 10 points once. 

It sometimes(!!!) works when I change the "/testrun" command like this:

```
command /testrun [<offlineplayer>]:
	trigger:
		loop 5 times:
			wait 1 tick
			make console execute command "/test"
```

Then it sometimes adds 30 points and another time it adds 40 points .. but that is very strange behaviour and seems very buggy to me.

**Comment by Govindass** [comment]
your sql query seems wrong, it should end with:
UPDATE `points` = `points`+%{_points}%

**Comment by GovindasOM** [comment]
I am closing this issue, please e-open it when it happens again
